language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t diogofnmachado/docker-react .

script:
  - docker run -e CI=true diogofnmachado/docker-react npm run test